[project]
name = 'inventory-financing'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.inventory-verifier]
path = 'contracts/inventory-verifier.clar'
clarity_version = 2
epoch = 2.5

[contracts.velocity-analyzer]
path = 'contracts/velocity-analyzer.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
